apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndn-k8s
  labels:
    app: ndn-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndn-k8s
  template:
    metadata:
      labels:
        app: ndn-k8s
    spec:
      containers:               
      - name: ndn-k8s
        image: cbmckni/ndn-tools
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/usr/local/bin/nfd -c $CONFIG > $LOG_FILE 2>&1 && tail -f /dev/null" ]
        resources:
          requests:
            cpu: 1
            memory: 4Gi
          limits:
            cpu: 1
            memory: 4Gi
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: vol-1
          mountPath: /workspace
      restartPolicy: Always
      volumes:
        - name: vol-1
          persistentVolumeClaim:
            claimName: scidas-dev # Enter valid PVC
---
kind: Service
apiVersion: v1
metadata:
  name: ndn-k8s
  labels:
    app: ndn-k8s
spec:
  type: ClusterIP
  selector:
    app: ndn-k8s
  ports:
  - port: 8080
    targetPort: 8080


