apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.Deployment.Name }}
  labels:
    app: {{ .Values.Deployment.Name }}
spec:
  serviceName: {{ .Values.Deployment.Name }}
  replicas: {{ .Values.Deployment.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Deployment.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.Name }}
    spec:
      containers:               
      - name: {{ .Values.Deployment.Name }}
        image: {{ .Values.Deployment.Image }}
        command: [ "/bin/sh", "-c", "--" ]
        args: [ {{ .Values.Deployment.Arg }} ]
        resources:
          requests:
            cpu: {{ .Values.Resources.Requests.CPU }}
            memory: {{ .Values.Resources.Requests.Memory }}
          limits:
            cpu: {{ .Values.Resources.Limits.CPU }}
            memory: {{ .Values.Resources.Limits.Memory }}
        volumeMounts:
          - name: pvc
            mountPath: /workspace
      restartPolicy: Always
{{ if .Values.ExistingRWXPVC.Enabled }}
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: {{ .Values.ExistingRWXPVC.Name }}
{{ end }}
{{ if .Values.PVCTemplates.Enabled }}
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.PVCTemplates.StorageClass }}
      resources:
        requests:
          storage: {{ .Values.PVCTemplates.Storage }}
{{ end }}
