# Declare variables to be passed into your templates.



# Deployment Settings

Deployment:
  Name: icn-lake-rice
  Image: ncbi/sra-tools
  Replicas: 1
  Arg: "
      apk update && apk upgrade && apk add --no-cache bash git openssh; rm -rf /workspace/pvc-data-loader; cd /workspace; git clone https://github.com/cbmckni/pvc-data-loader.git; chmod +x ./pvc-data-loader/scripts/rice.sh; ./pvc-data-loader/scripts/rice.sh 1"




# Resource Requests

Resources:
  Requests:
    CPU: 1
    Memory: 4Gi
  Limits:
    CPU: 1
    Memory: 4Gi

# ExistingReadWriteManyPVC Settings

ExistingRWXPVC:
  Enabled: true
  Name: pvc-storage-test

# PVC Template Settings

PVCTemplates:
  Enabled: false
  StorageClass: rook-ceph-block
  Storage: 750Gi # per pod

