# Declare variables to be passed into your templates.



# Deployment Settings

Deployment:
  Name: ndn-k8s-kidney
  Image: ncbi/sra-tools
  NodeSelector: 
    Enabled: false
    Arg: "kubernetes.io/hostname: epic001.clemson.edu" 
  Replicas: 36
  Arg: "
    printf '/LIBS/GUID = "%s"\n' `uuidgen` > /root/.ncbi/user-settings.mkfg && tail -f /dev/null"




# Resource Requests

Resources:
  Requests:
    CPU: 1
    Memory: 4Gi
  Limits:
    CPU: 1
    Memory: 4Gi



# PVC Template Settings

PVC:
  StorageClass: rook-cephfs
  Storage: 15Gi # per pod

