# Declare variables to be passed into your templates.



# Deployment Settings

Deployment:
  Name: ndn-k8s-example
  Image: cbmckni/ndn-tools
  NodeSelector: 
    Enabled: false
    Arg: "kubernetes.io/hostname: epic001.clemson.edu" 
  Replicas: 10
  Arg: "
    rm -rf /workspace/ndn && mkdir -p /workspace/ndn && \
    apt-get update -y && apt-get install -y git && \
    git clone --single-branch --branch statefulset https://github.com/cbmckni/ndn-k8s.git /workspace/ndn && \
    /workspace/ndn/genomics/scripts/sync.sh ndn-k8s-example && \
    /workspace/ndn/genomics/scripts/boot.sh && \
    /workspace/ndn/genomics/scripts/route.sh / ndn-k8s-producer-1gb && \
    /workspace/ndn/genomics/scripts/cat.sh -n /k8s/1gb -o /workspace/ndn/1GB.test -t /workspace/ndn/1GB.test.time && \
    /workspace/ndn/genomics/scripts/delay.sh
  "

# EXAMPLE PRODUCER: "
# /workspace/ndn/scripts/boot.sh &&
# /workspace/ndn/scripts/put.sh /k8s/pub/file /workspace/ndn/samples/1GB
# "

# EXAMPLE CONSUMER: "
# /workspace/ndn/scripts/boot.sh &&
# /workspace/ndn/scripts/route.sh / PRODUCER_NAME &&
# /workspace/ndn/scripts/cat.sh -n /k8s/pub/file -o /workspace/ndn/output/1GB.test -t /workspace/ndn/times/sample_tests &&
# /workspace/ndn/scripts/delay.sh
# "

# EXAMPLE MANUAL: "
# /workspace/ndn/scripts/boot.sh &&
# /workspace/ndn/scripts/delay.sh
# "




# Resource Requests

Resources:
  Requests:
    CPU: 1
    Memory: 4Gi
  Limits:
    CPU: 1
    Memory: 4Gi



# PVC Template Settings

PVC:
  StorageClass: rook-cephfs
  Storage: 5Gi # per pod

# Ingress control settings
Ingress:
  Enabled: false
  # The subdomain to associate with this service.
  Host: ndnlakev1.nautilus.optiputer.net
  # The class of the ingress controller to use.
  Class: traefik

