# Declare variables to be passed into your templates.


# Deployment Settings

Deployment:
  Name: ndn-k8s-test
  Image: cbmckni/ndn-tools
  Host: false # deploy to specific host vs "random"
  Hostname: epic001.clemson.edu
  Replicas: 1
  Arg: "/usr/local/bin/nfd -c $CONFIG > $LOG_FILE 2>&1 && tail -f /dev/null"
# EXAMPLE PRODUCER: "/usr/local/bin/nfd -c /workspace/nfd/nfd-producer.conf > $LOG_FILE 2>&1 && ndnputchunks /k8s/1GB < /workspace/1GB && ndnputchunks /k8s/5GB < /workspace/5GB && tail -f /dev/null"
# EXAMPLE CONSUMER: "/usr/local/bin/nfd -c $CONFIG > $LOG_FILE 2>&1 && nfdc face create tcp4://ndn-k8s-put1GB-cole && nfdc route add /k8s tcp4://ndn-k8s-put1GB-cole && ndncatchuncks /k8s/1GB > /tmp/1GB.tmp && tail -f /dev/null"
# EXAMPLE MANUAL: "/usr/local/bin/nfd -c $CONFIG > $LOG_FILE 2>&1 && tail -f /dev/null"

# Resource Requests

Resources:
  Requests:
    CPU: 1
    Memory: 4Gi
  Limits:
    CPU: 1
    Memory: 4Gi



# PVC Settings

ExistingPVC:
  # If true, use existing PVC on local cluster.
  Enabled: true
  Name: deepgtex-prp
  Path: /workspace

NewPVC:
  # If true, create new PVC on local cluster.
  Enabled: false
  Name: ndn-k8s-pvc-test
  Size: 50Gi
  StorageClass: nfs # Make sure storage class provisioner exists!
  Path: /workspace



# Ingress control settings
Ingress:
  Enabled: false
  # The subdomain to associate with this service.
  Host: ndnlakev1.nautilus.optiputer.net
  # The class of the ingress controller to use.
  Class: traefik

