# Declare variables to be passed into your templates.



# Deployment Settings

Deployment:
  Name: ndn-k8s-sample
  Image: cbmckni/ndn-tools
  Host: false # deploy to specific host vs "random"
  Hostname: epic001.clemson.edu
  Replicas: 1
  Arg: "/workspace/ndn/scripts/nfd.boot.sh && /workspace/ndn/scripts/delay.sh"
# EXAMPLE PRODUCER: "/workspace/ndn/scripts/nfd.boot.sh && /workspace/ndn/scripts/put.sh /k8s/1gb /workspace/ndn/samples/1GB"
# EXAMPLE CONSUMER: "/workspace/ndn/scripts/nfd.boot.sh && /workspace/ndn/scripts/cat.sh PRODUCER_NAME /k8s/1gb /workspace/ndn/output/1GB.test"
# EXAMPLE MANUAL: "/workspace/ndn/scripts/nfd.boot.sh && /workspace/ndn/scripts/delay.sh"



# Resource Requests

Resources:
  Requests:
    CPU: 1
    Memory: 4Gi
  Limits:
    CPU: 1
    Memory: 4Gi



# PVC Settings

ExistingPVC:
  # If true, use existing PVC on local cluster.
  Enabled: true
  Name: deepgtex-prp
  Path: /workspace

NewPVC:
  # If true, create new PVC on local cluster.
  Enabled: false
  Name: ndn-k8s-pvc-test
  Size: 50Gi
  StorageClass: nfs # Make sure storage class provisioner exists!
  Path: /workspace



# Ingress control settings
Ingress:
  Enabled: false
  # The subdomain to associate with this service.
  Host: ndnlakev1.nautilus.optiputer.net
  # The class of the ingress controller to use.
  Class: traefik

