# Declare variables to be passed into your templates.



# Deployment Settings

Deployment:
  Name: kidney-1
  Image: ncbi/sra-tools
  Replicas: 2
  Arg: "echo 'starting'; if [ -d /workspace/pvc-data-loader ]; then rm -rf /workspace/pvc-data-loader; fi; git clone https://github.com/cbmckni/pvc-data-loader.git /workspace/pvc-data-loader && cd /workspace/pvc-data-loader && time ./scripts/kidney.sh > total.txt; echo 'done'"




# Resource Requests

Resources:
  Requests:
    CPU: 1
    Memory: 4Gi
  Limits:
    CPU: 1
    Memory: 4Gi


# PVC Template Settings

PVC:
  StorageClass: rook-cephfs
  Storage: 150Gi # per pod

