# Declare variables to be passed into your templates.



# Deployment Settings

Deployment:
  Name: kidney-east
  Image: ncbi/sra-tools
  Replicas: 2
  Arg: "tail -f /dev/null"




# Resource Requests

Resources:
  Requests:
    CPU: 1
    Memory: 4Gi
  Limits:
    CPU: 1
    Memory: 4Gi



# PVC Template Settings

PVC:
  StorageClass: rook-cephfs-east
  Storage: 150Gi # per pod

